auto_save: false
dark_mode: true
display_label_popup: true
store_data: true
keep_prev: false
keep_prev_scale: true
keep_prev_brightness: true
keep_prev_contrast: true
logger_level: info
flags: [a, b, c]
label_flags:
labels: [house, boat, water, tower, person]
file_search:
sort_labels: true
validate_label: exact
default_shape_color: [0, 255, 0]
shape_color: auto
shift_auto_shape_color: 0
label_colors:
shape:
  # drawing
  drawing:
    line_color: [0, 255, 0, 128]
    fill_color: [0, 255, 0, 0]  # transparent
    vertex_fill_color: [0, 255, 0, 255]
    point_size: 8
  trace:
    # smoothness sets the intervalls at which points are drawn
    point_size: 2
    smothness: 11
  select:
    # epsilon sets the snapping distance for editing and deleting point
    line_color: [255, 255, 255, 255]
    fill_color: [0, 255, 0, 155]
    vertex_fill_color: [255, 255, 255, 255]
    epsilon: 15
    point_size: 12
flag_dock:
  show: false
  closable: true
  movable: true
  floatable: true
label_dock:
  show: false
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  num_backups: 10
shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to:
  delete_file: Ctrl+Delete
  open_next: [D, Ctrl+RIGHT]
  open_prev: [A, Ctrl+LEFT]
  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F
  create_polygon: Ctrl+N
  create_trace: Ctrl+T
  reset_trace:
  create_rectangle: Ctrl+R
  create_circle:
  create_line:
  create_point:
  create_linestrip:
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon:
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  undo: Ctrl+Z
  undo_last_point: Ctrl+Z
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
  remove_selected_point: Backspace
